# Generated by Django 5.2.14 on 2026-05-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_schedule_token_cleanup"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserprofile",
            name="deletion_requested_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="deletion requested at"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="deletion_requested_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="deletion requested at"
            ),
        ),
    ]
