# Generated by Django 5.2.14 on 2026-05-21 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_deletion_requested_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserprofile",
            name="email_verification_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="email verification sent at"
            ),
        ),
        migrations.AddField(
            model_name="historicaluserprofile",
            name="email_verification_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=64,
                verbose_name="email verification token",
            ),
        ),
        migrations.AddField(
            model_name="historicaluserprofile",
            name="email_verified",
            field=models.BooleanField(default=False, verbose_name="email verified"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_verification_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="email verification sent at"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_verification_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=64,
                verbose_name="email verification token",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_verified",
            field=models.BooleanField(default=False, verbose_name="email verified"),
        ),
    ]
