# Generated by Django 5.2.14 on 2026-05-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_backfill_email_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googleidentity",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_column="created_at",
                db_index=True,
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="googleidentity",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_column="updated_at", verbose_name="updated at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalgoogleidentity",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_column="created_at",
                db_index=True,
                editable=False,
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="historicalgoogleidentity",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_column="updated_at",
                editable=False,
                verbose_name="updated at",
            ),
        ),
    ]
