# Generated by Django 5.0.9 on 2026-05-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0006_increase_maps_url_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="coords_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("resolved", "Resolved"),
                    ("failed", "Failed"),
                ],
                db_column="coords_status",
                default="resolved",
                max_length=10,
                verbose_name="coords status",
            ),
        ),
    ]
