# Generated by Django 5.2.14 on 2026-05-11 15:12

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0008_soft_delete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPlace",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="created_at",
                        db_index=True,
                        editable=False,
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="updated_at",
                        editable=False,
                        verbose_name="updated at",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="deleted_at",
                        null=True,
                        verbose_name="deleted at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="name", max_length=200, verbose_name="name"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        db_column="category", max_length=100, verbose_name="category"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        db_column="address",
                        max_length=300,
                        verbose_name="address",
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True,
                        db_column="instagram_url",
                        verbose_name="instagram url",
                    ),
                ),
                (
                    "maps_url",
                    models.URLField(
                        blank=True,
                        db_column="maps_url",
                        max_length=2000,
                        verbose_name="maps url",
                    ),
                ),
                (
                    "coords_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("resolved", "Resolved"),
                            ("failed", "Failed"),
                        ],
                        db_column="coords_status",
                        default="resolved",
                        max_length=10,
                        verbose_name="coords status",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        db_column="latitude",
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        db_column="longitude",
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="longitude",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("want_to_visit", "Want to visit"),
                            ("visited", "Visited"),
                            ("favorite", "Favorite"),
                            ("would_not_return", "Would not return"),
                        ],
                        db_column="status",
                        default="want_to_visit",
                        max_length=32,
                        verbose_name="status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, db_column="notes", verbose_name="notes"
                    ),
                ),
                (
                    "cover_photo",
                    models.TextField(
                        blank=True,
                        db_column="cover_photo",
                        max_length=100,
                        null=True,
                        verbose_name="cover photo",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_id",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical place",
                "verbose_name_plural": "historical places",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalVisit",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="created_at",
                        db_index=True,
                        editable=False,
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="updated_at",
                        editable=False,
                        verbose_name="updated at",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="deleted_at",
                        null=True,
                        verbose_name="deleted at",
                    ),
                ),
                (
                    "visited_at",
                    models.DateTimeField(
                        db_column="visited_at", db_index=True, verbose_name="visited at"
                    ),
                ),
                (
                    "environment_rating",
                    models.DecimalField(
                        blank=True,
                        db_column="environment_rating",
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("10")),
                        ],
                        verbose_name="environment rating",
                    ),
                ),
                (
                    "service_rating",
                    models.DecimalField(
                        blank=True,
                        db_column="service_rating",
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("10")),
                        ],
                        verbose_name="service rating",
                    ),
                ),
                (
                    "overall_rating",
                    models.DecimalField(
                        blank=True,
                        db_column="overall_rating",
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("10")),
                        ],
                        verbose_name="overall rating",
                    ),
                ),
                (
                    "would_return",
                    models.BooleanField(
                        db_column="would_return",
                        default=True,
                        verbose_name="would return",
                    ),
                ),
                (
                    "general_notes",
                    models.TextField(
                        blank=True,
                        db_column="general_notes",
                        verbose_name="general notes",
                    ),
                ),
                (
                    "photo",
                    models.TextField(
                        blank=True,
                        db_column="photo",
                        max_length=100,
                        null=True,
                        verbose_name="photo",
                    ),
                ),
                (
                    "photo_path",
                    models.CharField(
                        blank=True,
                        db_column="photo_path",
                        max_length=500,
                        verbose_name="photo path",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        db_column="place_id",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="places.place",
                        verbose_name="place",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical visit",
                "verbose_name_plural": "historical visits",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalVisitItem",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="created_at",
                        db_index=True,
                        editable=False,
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="updated_at",
                        editable=False,
                        verbose_name="updated at",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="deleted_at",
                        null=True,
                        verbose_name="deleted at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="name", max_length=200, verbose_name="name"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sweet", "Sweet"),
                            ("savory", "Savory"),
                            ("drink", "Drink"),
                            ("coffee", "Coffee"),
                            ("juice", "Juice"),
                            ("dessert", "Dessert"),
                            ("other", "Other"),
                        ],
                        db_column="type",
                        default="other",
                        max_length=32,
                        verbose_name="type",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        db_column="rating",
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("10")),
                        ],
                        verbose_name="rating",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        db_column="price",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="price",
                    ),
                ),
                (
                    "would_order_again",
                    models.BooleanField(
                        db_column="would_order_again",
                        default=True,
                        verbose_name="would order again",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, db_column="notes", verbose_name="notes"
                    ),
                ),
                (
                    "photo",
                    models.TextField(
                        blank=True,
                        db_column="photo",
                        max_length=100,
                        null=True,
                        verbose_name="photo",
                    ),
                ),
                (
                    "photo_path",
                    models.CharField(
                        blank=True,
                        db_column="photo_path",
                        max_length=500,
                        verbose_name="photo path",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        db_column="visit_id",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="places.visit",
                        verbose_name="visit",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical visit item",
                "verbose_name_plural": "historical visit items",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
