# Generated by Django 5.2.14 on 2026-05-15 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0009_historicalplace_historicalvisit_historicalvisititem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                fields=["user", "deleted_at"], name="place_user_deleted_at_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(
                fields=["place", "deleted_at"], name="visit_place_deleted_at_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visititem",
            index=models.Index(
                fields=["visit", "deleted_at"], name="visititem_visit_deleted_at_idx"
            ),
        ),
    ]
