# Generated by Django 5.2.14 on 2026-05-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0015_schedule_media_compression"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_column="created_at",
                db_index=True,
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_column="updated_at", verbose_name="updated at"
            ),
        ),
    ]
