# Generated by Django 5.2.14 on 2026-05-25 21:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0019_expand_collection_share_snapshot_lengths_to_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=100, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'places_category',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PlaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'db_table': 'places_place_category',
            },
        ),
        migrations.RemoveIndex(
            model_name='place',
            name='place_user_category_idx',
        ),
        migrations.RemoveIndex(
            model_name='place',
            name='place_category_trgm_idx',
        ),
        migrations.RemoveField(
            model_name='historicalplace',
            name='category',
        ),
        migrations.RemoveField(
            model_name='place',
            name='category',
        ),
        migrations.AddField(
            model_name='placecategory',
            name='category',
            field=models.ForeignKey(db_column='id_category', on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='places.category'),
        ),
        migrations.AddField(
            model_name='placecategory',
            name='place',
            field=models.ForeignKey(db_column='id_place', on_delete=django.db.models.deletion.CASCADE, related_name='plance_links', to='places.place'),
        ),
        migrations.AddField(
            model_name='place',
            name='categories',
            field=models.ManyToManyField(through='places.PlaceCategory', through_fields=('place', 'category'), to='places.category'),
        ),
    ]
